name: Fiefdom
version: 0.00
description: Land/property management
author: JavaWarlord
website: www.valiantmarauders.com
main: com.valiantmarauders.minecraft.fiefdom.Fiefdom
commands:
  nospawn:
    description: Main command
    aliases: [Fiefdom]
    usage: 
      /<command> [parameters]
